### ISSUE TITLE
[Feature request] Mac version?

### ISSUE THREAD

**Issue by DeliciousPickle** [JumpFm/jumpfm#10]
Since this is an Electron app, would you consider releasing a Mac build?  Or, is there a way to make the Linux build work on a Mac?  If it has a lot of Linux dependencies, you could distribute it via Homebrew.

**Comment by heywoodlh** [comment]
Agreed! ^^

**Comment by gkutiel** [comment]
I don't own a Mac machine (and don't plan to in the near future), so unfortunately I can't help with this. 
It should be, however, straight forward to do that for someone with a Mac. If someone is willing to pick up the glove that will be really great.

**Comment by heywoodlh** [comment]
I'm willing to volunteer my Mac if I get a little guidance. I'm not a developer by any means, but if I had some assistance in knowing where to start I think I could get it built. 

_Sent from my Samsung SM-G955U1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by heywoodlh** [comment]
I was able to get it up and running on my Mac without issue. I'll be testing to make sure that everything works properly and then once I feel it is ready I'll try to package a dmg and submit a pull request.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/18178614/29751963-5b2b665a-8b12-11e7-9777-1aae90feeec0.png">

**Comment by heywoodlh** [comment]
Most things work. I packaged the dmg which is currently here: https://github.com/heywoodlh/jumpfm/releases. 

Two things of note:
1. substitute the command key for ctrl in the keyboard shortcuts.
2. copy and paste doesn't work yet. I will work on that.

**Comment by gkutiel** [comment]
Great Job !!!
- Is it possible to just download and run the ```.dmg``` release ?

**Comment by heywoodlh** [comment]
Yes. The .dmg file has .app folder with a binary in it. And when opening the dmg it prompts the user to place the .app folder in /Applications. Which is a part of $PATH. 

I tested it on my Mac and it worked perfect. And I tested the copying of the path in Jumpfm so that actually does work. So I don't really know of any other problems specific to the Mac version. If in the future you'd like me to package updated versions I absolutely can.

Overall, I think you can consider this closed as it seems like everything is working.
