### ISSUE TITLE
Not working on Manjaro 17 or Ubuntu 16.04.3

### ISSUE THREAD

**Issue by yaron-tracxpoint** [JumpFm/jumpfm#9]
I tried installing using the AppImage file on Ubuntu and I got a blank screen with the path of my home directory on top:
![screenshot_2017-08-23_15-49-48](https://user-images.githubusercontent.com/31091476/29616594-b78931ac-881a-11e7-8ed7-9f1a81f46e90.png)
(After the plugins update the message about the updated disappear but the interface remains the same)

Then I tried on Manjaro (Arch derivative) using this AUR script:
https://aur.archlinux.org/packages/jumpfm-bin/

After installing I tried running the file manager from the command line just to see the stdout while the program is running and I saw the following messages (Sorry I can't copy, there's a problem with selecting using the cursor):
![screenshot_2017-08-23_15-47-09](https://user-images.githubusercontent.com/31091476/29616717-11836a1a-881b-11e7-9709-2cfd7649b05a.png)

**Comment by gkutiel** [comment]
Please try ```rm -rf ~/.jumpfm``` and then installing the [latest release](https://github.com/JumpFm/jumpfm/releases/latest)

Let me know if it fixes the problem.

**Comment by yaron-tracxpoint** [comment]
I did that exactly, I ran `yaourt -S jumpfm-bin`, the package was updated to the latest version available (1.0.3).

The app shows the Downloading plugins prompt, after a while the prompt disappears, I'm looking at the .jumpfm folder and I see the package.json and node_modules folder, the package.json is populated with a json list of required dependencies while the node_modules folder is empty.

When running from CLI I'm seeing the following message:
Update for linux-x64-prod-v1.0.3 is not available

Am I doing anything wrong?
Are there any debug arguments I can run to see verbose output?

Thanks!

**Comment by gkutiel** [comment]
Did you try to completely remove the settings folder ? i.e.
```rm -rf ~/.jumpfm```
Or something equivalent ?

**Comment by yarons** [comment]
Sure (Sorry I'm using my other account).
I did delete that, apparently that wasn't the problem, there were some connectivity issues with npm repositories, I fixed that and everything went back to normal afterwards.

The reason I had no idea that happened was I had to launch it via CLI in order to see the error, when I launched the app without the CLI in background I just saw some progress being done and for no reason the progress got stopped but nothing happened to the UI, which makes you wonder if anything wrong happened but you can't be sure.

So I'm guessing that having some sort of "catch" (or simply reading the error code) after the npm install procedure will at least give the user some hint about that although it's not your fault at all.

**Comment by gkutiel** [comment]
There will be error feedback in the next version, #17
